/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#7bd0ff",
        "primary": "#ffb690",
        "on-tertiary-fixed": "#001e2c",
        "tertiary-container": "#00a6df",
        "error-container": "#93000a",
        "surface-bright": "#353942",
        "on-primary": "#552100",
        "primary-container": "#f97316",
        "on-background": "#dfe2ee",
        "outline-variant": "#584237",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#2f2ebe",
        "secondary-container": "#3131c0",
        "inverse-surface": "#dfe2ee",
        "on-secondary-fixed": "#07006c",
        "on-tertiary-container": "#00374d",
        "inverse-primary": "#9d4300",
        "surface-container-lowest": "#0a0e16",
        "primary-fixed-dim": "#ffb690",
        "on-primary-container": "#582200",
        "on-primary-fixed": "#341100",
        "on-secondary": "#1000a9",
        "surface-container-low": "#181c24",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#c0c1ff",
        "on-primary-fixed-variant": "#783200",
        "surface-container-highest": "#31353e",
        "outline": "#a78b7d",
        "on-secondary-container": "#b0b2ff",
        "surface-container": "#1c2028",
        "tertiary-fixed-dim": "#7bd0ff",
        "background": "#0f131c",
        "tertiary-fixed": "#c4e7ff",
        "on-error-container": "#ffdad6",
        "surface": "#0f131c",
        "secondary": "#c0c1ff",
        "surface-dim": "#0f131c",
        "primary-fixed": "#ffdbca",
        "on-surface-variant": "#e0c0b1",
        "secondary-fixed": "#e1e0ff",
        "on-tertiary": "#00354a",
        "on-tertiary-fixed-variant": "#004c69",
        "surface-tint": "#ffb690",
        "on-surface": "#dfe2ee",
        "surface-variant": "#31353e",
        "inverse-on-surface": "#2c3039",
        "surface-container-high": "#262a33"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.25rem",
        "space-2xl": "1.5rem",
        "space-3xl": "2rem",
        "gutter": "0.75rem",
        "sidebar-width": "15rem",
        "sidebar-collapsed": "3.5rem",
        "margin-screen": "1rem"
      },
      fontFamily: {
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-xs": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "metric-display": ["JetBrains Mono", "monospace"],
        "metric-md": ["JetBrains Mono", "monospace"],
        "code-xs": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "700" }],
        "body-xs": ["11px", { lineHeight: "14px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-md": ["15px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["13px", { lineHeight: "18px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "metric-display": ["28px", { lineHeight: "32px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "metric-md": ["16px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "code-xs": ["10.5px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["18px", { lineHeight: "24px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-xl": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "code-sm": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "500" }],
        "body-md": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
